name: rikin_interview_14_02
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  auto_route: ^9.3.0
  flutter_bloc: ^9.0.0

  #UTIL
  oktoast: ^3.4.0
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  colorize: ^3.0.0
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  intl: ^0.20.2
  
  #UI
  ndialog: ^4.4.0

  # NETWORK
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2

  #FIREBASE
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  freezed: ^2.5.8

flutter:
  uses-material-design: true
